name: Update and Merge EPG XMLs Daily

on:
  schedule:
    - cron: '0 2 * * *'  # runs every day at 2 AM UTC
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download EPG files
      run: |
        curl -o epg1.xml "https://epg.pw/api/epg.xml?channel_id=403626"
        curl -o epg2.xml "https://epg.pw/api/epg.xml?channel_id=400477"
        curl -o epg3.xml "https://epg.pw/api/epg.xml?channel_id=400480"
        curl -o epg4.xml "https://epg.pw/api/epg.xml?channel_id=405060"
        curl -o epg5.xml "https://epg.pw/api/epg.xml?channel_id=405134"

    - name: Merge EPG files
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>' > merged_epg.xml
        echo '<tv>' >> merged_epg.xml
        # remove <tv> and </tv> tags from each file and append contents
        grep -v '<?xml' epg1.xml | sed '/<tv>/d; /<\/tv>/d' >> merged_epg.xml
        grep -v '<?xml' epg2.xml | sed '/<tv>/d; /<\/tv>/d' >> merged_epg.xml
        grep -v '<?xml' epg3.xml | sed '/<tv>/d; /<\/tv>/d' >> merged_epg.xml
        grep -v '<?xml' epg4.xml | sed '/<tv>/d; /<\/tv>/d' >> merged_epg.xml
        grep -v '<?xml' epg5.xml | sed '/<tv>/d; /<\/tv>/d' >> merged_epg.xml
        echo '</tv>' >> merged_epg.xml

    - name: Commit and push merged file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add merged_epg.xml
        git commit -m "Update merged EPG XML - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git push origin HEAD:main
