name: Update EPG XML daily

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download EPG XML
      run: curl -o epg.xml "https://epg.pw/api/epg.xml?channel_id=403626"

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add epg.xml
        git commit -m "Update EPG XML - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
